services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - 3000:3000

  api:
    build: .
    # ports:
    #   - "3000:3000"
    depends_on:
      minio:
        condition: service_healthy
    environment:
      PORT: 3000
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ALIAS: myminio
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin &&
      npm start"
    user: root
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  minio_storage:
